convert:
	convert -density 30 correlation.png correlation.eps
	convert -density 30 Correlation_examples.png Correlation_examples.eps
	convert -density 300 distribution_functions.eps distribution_functions.png
